language: php

php:
  - 7.3
  - 8.0
dist: focal
# branches:
#   only:
#     - master
env:
  - DOCKER_COMPOSE_VERSION=1.25.5

sudo: required

services:
  - docker

before_script:
  - sudo rm -rf /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose up -d
  - sudo chown -R $USER composer.json
  - chown -R www-data:www-data .
  # - sudo chown -R $USER composer.lock
  - sudo docker exec -t micro-videos-app composer install
  - ls -l
  # - sudo docker exec -t micro-videos-app composer install
  # - sudo docker exec -t micro-videos-app cp .env.example .env
  - sudo docker exec -t micro-videos-app php artisan key:generate
  - sudo docker exec -t micro-videos-app php artisan migrate
  - sudo docker exec -t micro-videos-app php vendor/bin/phpunit -c phpunit.xml

  # - apt-get install docker-compose
  # - cp .env.example .env
  # - composer install
  # - php artisan key:generate
  # - php artisan migrate
script:
  # - sudo chown -R $USER composer.json
  # - sudo chown -R $USER composer.lock
  # - sudo docker exec -t micro-videos-app composer install
  # - ls -l
  # - sudo docker exec -t micro-videos-app composer install
  # - sudo docker exec -t micro-videos-app cp .env.example .env
  # - sudo docker exec -t micro-videos-app php artisan key:generate
  # - sudo docker exec -t micro-videos-app php artisan migrate
  # - sudo docker exec -t micro-videos-app php vendor/bin/phpunit -c phpunit.xml

# after_success:
#   - ./scripts/dotnet-publish.sh
#   - ./scripts/docker-publish.sh
# notifications:
#   email:
#     on_success: never
#     on_failure: always
