version: '3.7'

services:
  app:
    build:
        context: ./.docker/app
        dockerfile: Dockerfile
    container_name: micro-videos-app
    volumes:
      - ./:/var/www
    networks:
      - app-network
    depends_on:
      - db
      - redis

  nginx:
    build:
      context: ./.docker/nginx
      dockerfile: dockerfile
    container_name: micro-videos-nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
    networks:
      - app-network

  db:
    build:
      context: ./.docker/mysql
      dockerfile: dockerfile
    container_name: micro-videos-db
    restart: always
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=code_micro_videos
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: micro-videos-redis
    expose:
      - 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
